<?php

const QUERIES = [
    "add_user" => "INSERT INTO user (username, `password`, `name`, surname) VALUES (?, ?, ?, ?)",
    "add_user_email" => "INSERT INTO user (username, `password`, `name`, surname, email) VALUES (?, ?, ?, ?, ?)",
    "add_user_phone" => "INSERT INTO user (username, `password`, `name`, surname, phone) VALUES (?, ?, ?, ?, ?)",
    "add_user_birthdate" => "INSERT INTO user (username, `password`, `name`, surname, birthdate) VALUES (?, ?, ?, ?, ?)",
    "add_user_email_phone" => "INSERT INTO user (username, `password`, `name`, surname, email, phone) VALUES (?, ?, ?, ?, ?, ?)",
    "add_user_email_birthdate" => "INSERT INTO user (username, `password`, `name`, surname, email, birthdate) VALUES (?, ?, ?, ?, ?, ?)",
    "add_user_phone_birthdate" => "INSERT INTO user (username, `password`, `name`, surname, phone, birthdate) VALUES (?, ?, ?, ?, ?, ?)",
    "add_user_email_phone_birthdate" => "INSERT INTO user (username, `password`, `name`, surname, email, phone, birthdate) VALUES (?, ?, ?, ?, ?, ?, ?)",
    "update_user_username" => "UPDATE user SET username = ? WHERE username = ?",
    "update_user_password" => "UPDATE user SET `password` = ? WHERE username = ?",
    "update_user_name" => "UPDATE user SET `name` = ? WHERE username = ?",
    "update_user_surname" => "UPDATE user SET surname = ? WHERE username = ?",
    "update_user_email" => "UPDATE user SET email = ? WHERE username = ?",
    "update_user_phone" => "UPDATE user SET phone = ? WHERE username = ?",
    "update_user_birthdate" => "UPDATE user SET birthdate = ? WHERE username = ?",
    "update_user_profile_image" => "UPDATE user SET profile_image = ? WHERE username = ?",
    "delete_user" => "DELETE FROM user WHERE username = ?",
    "check_username" => "SELECT username FROM user WHERE username = ?",
    "get_password" => "SELECT `password` FROM user WHERE username = ?",
    "get_feed_posts" => "SELECT p.post_id, p.caption, p.`timestamp`, p.username AS owner, pl.username, pr.username AS rated FROM post p LEFT JOIN post_like pl ON p.post_id = pl.post_id AND pl.username = ? LEFT JOIN post_rating pr ON p.post_id = pr.post_id AND pr.username = ? WHERE p.username IN (SELECT to_username FROM `following` WHERE from_username = ?) ORDER BY p.`timestamp` DESC LIMIT ?, ?",
    "get_user" => "SELECT * FROM user WHERE username = ?",
    "get_user_followers" => "SELECT * FROM user WHERE username IN (SELECT from_username AS username FROM following WHERE to_username = ?)",
    "get_user_following" => "SELECT * FROM user WHERE username IN (SELECT to_username AS username FROM following WHERE from_username = ?)",
    "get_post_likes_people" => "SELECT * FROM user WHERE username IN (SELECT username FROM post_like WHERE post_id = ?)",
    "like_post" => "INSERT INTO post_like (post_id, username) VALUES (?, ?)",
    "unlike_post" => "DELETE FROM post_like WHERE post_id = ? AND username = ?",
    "get_post_likes" => "SELECT * FROM post_like WHERE post_id = ? ORDER BY `timestamp` DESC",
    "comment_post" => "INSERT INTO comment (post_id, `text`, username) VALUES (?, ?, ?)",
    "get_post" => "SELECT * FROM post WHERE post_id = ?",
    "delete_comment" => "DELETE FROM comment WHERE comment_id = ?",
    "get_post_comments" => "SELECT c.*, cl.username AS liked FROM comment c LEFT JOIN comment_like cl ON c.comment_id = cl.comment_id AND cl.username = ? WHERE c.post_id = ? ORDER BY `timestamp` DESC",
    "add_post" => "INSERT INTO post (caption, username, location, device) VALUES (?, ?, ?, ?)",
    "delete_post" => "DELETE FROM post WHERE post_id = ?",
    "get_user_posts" => "SELECT p.post_id, p.caption, p.`timestamp`, p.username AS owner, pl.username, pr.username AS rated FROM post p LEFT JOIN post_like pl ON p.post_id = pl.post_id AND pl.username = ? LEFT JOIN post_rating pr ON p.post_id = pr.post_id AND pr.username = ? WHERE p.username = ? ORDER BY p.`timestamp` DESC LIMIT ?, ?",
    "like_comment" => "INSERT INTO comment_like (comment_id, username) VALUES (?, ?)",
    "unlike_comment" => "DELETE FROM comment_like WHERE comment_id = ? AND username = ?",
    "get_post_images" => "SELECT * FROM post_image WHERE post_id = ?",
    "get_post_first_image" => "SELECT `image` FROM post_image WHERE post_id = ? AND position = 0",
    "add_post_image" => "INSERT INTO post_image (post_id, position, `image`) VALUES (?, ?, ?)",
    "get_user_notifications" => "SELECT n.*, u.profile_image FROM notification n LEFT JOIN user u ON n.sender = u.username WHERE receiver = ? ORDER BY `timestamp` DESC",
    "get_not_seen_notifications_number" => "SELECT COUNT(*) AS number FROM notification WHERE receiver = ? AND seen = 0",
    "set_notifications_seen" => "UPDATE notification SET seen = 1 WHERE receiver = ?",
    "delete_notification" => "DELETE FROM notification WHERE notification_id = ?",
    "delete_user_notifications" => "DELETE FROM notification WHERE receiver = ?",
    "send_notification" => "INSERT INTO notification (`text`, receiver, sender) VALUES (?, ?, ?)",
    "get_user_profile_image" => "SELECT profile_image FROM user WHERE username = ?",
    "get_matching_users" => "SELECT username, profile_image FROM user WHERE username LIKE ?",
    "get_user_followers_number" => "SELECT COUNT(*) AS number FROM `following` WHERE to_username = ?",
    "get_user_following_number" => "SELECT COUNT(*) AS number FROM `following` WHERE from_username = ?",
    "follow_user" => "INSERT INTO `following` (from_username, to_username) VALUES (?, ?)",
    "unfollow_user" => "DELETE FROM `following` WHERE from_username = ? AND to_username = ?",
    "get_if_user_liked_post" => "SELECT * FROM post_like WHERE post_id = ? AND username = ?",
    "get_post_likes_number" => "SELECT COUNT(*) AS likes_number FROM post_like WHERE post_id = ?",
    "get_user_posts_number" => "SELECT COUNT(*) AS number FROM post WHERE username = ?",
    "is_following" => "SELECT * FROM `following` WHERE from_username = ? AND to_username = ?",
];
